import SocialMediaIcon, { Media } from "../SocialMediaIcon/SocialMediaIcon";

export default function Footer() {
  return (
    <footer className="flex items-center justify-between p-8 px-24 mt-24 text-xs text-gray-400">
      <div>2024 &copy;</div>
      <div>Inspirational quotes are generated by a sleepy brain</div>
      <div className="flex items-center justify-center gap-2">
        <SocialMediaIcon
          media={Media.GitHub}
          href="https://github.com/iwnqkvqg?tab=repositories"
        />
      </div>
    </footer>
  );
}
